### PR TITLE
pwa native mobile functionality added (how to test in comments)

### PR DESCRIPTION
**Pull request by wgimson**
@alexgimson86  - The app now functions as a native app on mobile, has a service worker for caching, etc.
``
**-- TO TEST --**

1.   pull down this branch 
2.  run` npm start`
3.  In Chrome right click and open inspector. In the far left corner select mobile view
4. image
5.Then Select the Lighthouse tab on the far right.
6. image
7. the PWA report should pass for everything except using HTTPS, which will be implemented when we deploy.

### CODE REVIEW

**Comment by wgimson** [comment]
@alexgimson86 
Also make sure when you pull down this branch locally that there are no errors on the chrome console before we approve for merge with **Dev**.

**Comment by wgimson** [comment]
test comment....

**Comment by wgimson** [comment]
sweet we're integrated into #source-control on slack

**Review by alexgimson86 — APPROVED** [review]
looks good to me

**Comment by wgimson** [comment]
@alexgimson86 Does it run fine on your local?

**Pull request merged**
